name: DSView Container Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  cd:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Docker login
      run: docker login -u ${{ secrets.DOCKER_HUB_USER }} -p ${{ secrets.DOCKER_HUB_PASSWORD }}
    - name: Build
      run: docker build -t dsview ./docker
    - name: Tags
      run: |
        docker tag dsview ${{ secrets.DOCKER_HUB_USER }}/dsview:${{ github.sha }}
        docker tag dsview ${{ secrets.DOCKER_HUB_USER }}/dsview:latest
    - name: Push
      run: |
        docker push ${{ secrets.DOCKER_HUB_USER }}/dsview:${{ github.sha }}
        docker push ${{ secrets.DOCKER_HUB_USER }}/dsview:latest

